// <auto-generated />
//
// This file was automatically generated by PocosGenerator.csx, inspired from the PetaPoco T4 Template
// Do not make changes directly to this file - edit the PocosGenerator.GenerateClass() method in the PocosGenerator.Core.csx file instead
// 

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace api.IFTool.Models
{
  

    [Table("ProjectDeploy")]
    public partial class ProjectDeploy
    {
        public string branch { get; set; }
        public string project { get; set; }
        public string dev_env { get; set; }
        public string uat_env { get; set; }
        public string prd_env { get; set; }
        public string dev_project { get; set; }
        public string uat_project { get; set; }
        public string prd_project { get; set; }

    }
}
